# Generated by Django 5.2.15 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0125_work_item_property_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectworkitemproperty",
            name="multi_select_source",
            field=models.CharField(
                choices=[("MANUAL", "Manual list"), ("MEMBERS", "Project members")],
                default="MANUAL",
                max_length=16,
            ),
        ),
    ]
