# Generated by Django 5.2.15 on 2026-08-06 16:02

import django.db.models.deletion
import plane.db.models.state_transition
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_rename_work_item_select_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStateTransitionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_type', models.CharField(choices=[('EXACT', 'Exact status'), ('ANY', 'Any status'), ('CREATE', 'Work item creation')], max_length=16)),
                ('allow_conditions', models.JSONField(default=plane.db.models.state_transition.get_empty_transition_condition_tree)),
                ('deny_conditions', models.JSONField(default=plane.db.models.state_transition.get_empty_transition_condition_tree)),
                ('validation_conditions', models.JSONField(default=plane.db.models.state_transition.get_empty_transition_condition_tree)),
                ('project_admin_bypass', models.BooleanField(default=False)),
                ('system_bypass', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('source_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transition_rules', to='db.state')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transition_rules', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project State Transition Rule',
                'verbose_name_plural': 'Project State Transition Rules',
                'db_table': 'project_state_transition_rules',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectStateTransitionAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('CONFIGURATION_CHANGED', 'Configuration changed'), ('TRANSITION_DENIED', 'Transition denied')], max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transition_audit_logs', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('source_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transition_audit_logs', to='db.state')),
                ('target_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_transition_audit_logs', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='db.projectstatetransitionrule')),
            ],
            options={
                'verbose_name': 'Project State Transition Audit Log',
                'verbose_name_plural': 'Project State Transition Audit Logs',
                'db_table': 'project_state_transition_audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectStateTransitionSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('strict_mode', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project State Transition Settings',
                'verbose_name_plural': 'Project State Transition Settings',
                'db_table': 'project_state_transition_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='projectstatetransitionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_state__isnull', False), ('source_type', 'EXACT')), models.Q(('source_state__isnull', True), ('source_type__in', ['ANY', 'CREATE'])), _connector='OR'), name='valid_state_transition_rule_source'),
        ),
        migrations.AddConstraint(
            model_name='projectstatetransitionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True), ('source_type', 'EXACT')), fields=('project', 'source_state', 'target_state'), name='unique_active_exact_state_transition'),
        ),
        migrations.AddConstraint(
            model_name='projectstatetransitionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True), ('source_type__in', ['ANY', 'CREATE'])), fields=('project', 'source_type', 'target_state'), name='unique_active_global_state_transition'),
        ),
        migrations.AddIndex(
            model_name='projectstatetransitionauditlog',
            index=models.Index(fields=['project', 'action', '-created_at'], name='state_transition_audit_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstatetransitionsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='unique_active_state_transition_settings'),
        ),
    ]
