# Generated by Django 5.2.15 on 2026-08-07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


MEBIBYTE = 1024 * 1024


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0128_project_state_transition_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAttachmentSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "image_max_size",
                    models.PositiveBigIntegerField(blank=True, default=20 * MEBIBYTE, null=True),
                ),
                (
                    "video_max_size",
                    models.PositiveBigIntegerField(blank=True, default=500 * MEBIBYTE, null=True),
                ),
                (
                    "audio_max_size",
                    models.PositiveBigIntegerField(blank=True, default=100 * MEBIBYTE, null=True),
                ),
                (
                    "pdf_max_size",
                    models.PositiveBigIntegerField(blank=True, default=50 * MEBIBYTE, null=True),
                ),
                (
                    "document_max_size",
                    models.PositiveBigIntegerField(blank=True, default=50 * MEBIBYTE, null=True),
                ),
                (
                    "archive_max_size",
                    models.PositiveBigIntegerField(blank=True, default=200 * MEBIBYTE, null=True),
                ),
                (
                    "other_max_size",
                    models.PositiveBigIntegerField(blank=True, default=25 * MEBIBYTE, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Attachment Settings",
                "verbose_name_plural": "Project Attachment Settings",
                "db_table": "project_attachment_settings",
            },
        ),
        migrations.AddConstraint(
            model_name="projectattachmentsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project",),
                name="unique_active_project_attachment_settings",
            ),
        ),
    ]
