# Generated by Django 5.2.15 on 2026-08-16 11:27

import django.db.models.deletion
import django.utils.timezone
import plane.db.models.notification
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_user_full_name_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('task_assignment', models.BooleanField(default=True)),
                ('mention', models.BooleanField(default=True)),
                ('comment', models.BooleanField(default=True)),
                ('state_change', models.BooleanField(default=True)),
                ('issue_completed', models.BooleanField(default=True)),
                ('priority', models.BooleanField(default=True)),
                ('due_date', models.BooleanField(default=True)),
                ('property_change', models.BooleanField(default=True)),
                ('role_change', models.BooleanField(default=True)),
                ('account_activity', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours', models.JSONField(default=plane.db.models.notification.get_default_telegram_quiet_hours)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('bot_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('paused', 'Paused'), ('error', 'Error')], default='connected', max_length=20)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_user_connections',
                'ordering': ('-connected_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_link_tokens',
                'indexes': [models.Index(fields=['token_hash', 'expires_at'], name='tg_link_token_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('issue_id', models.UUIDField(blank=True, null=True)),
                ('category', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_deliveries', to='db.notification')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deliveries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.workspace')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='db.telegramuserconnection')),
            ],
            options={
                'db_table': 'telegram_deliveries',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='tg_delivery_due_idx'), models.Index(fields=['receiver', 'status'], name='tg_delivery_user_idx')],
            },
        ),
    ]
