# Generated by Django 5.2.15 on 2026-08-17 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_telegram_notifications'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='issue',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='access_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_inheritors', to='db.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='inherit_parent_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='visibility',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('RESTRICTED', 'Restricted')], db_index=True, default='PROJECT', max_length=16),
        ),
        migrations.CreateModel(
            name='IssueAccessAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('VISIBILITY_CHANGED', 'Visibility changed'), ('GROUPS_CHANGED', 'Allowed groups changed'), ('ASSIGNEES_CHANGED', 'Assignees changed'), ('MEMBER_PROPERTIES_CHANGED', 'Member properties changed'), ('GROUP_MEMBERS_CHANGED', 'Group members changed'), ('PARENT_ACCESS_APPLIED', 'Parent access applied')], max_length=48)),
                ('source_type', models.CharField(choices=[('VISIBILITY', 'Visibility'), ('CREATOR', 'Creator'), ('ASSIGNEE', 'Assignee'), ('MEMBER_PROPERTY', 'Member property'), ('USER_GROUP', 'User group'), ('GROUP_MEMBERSHIP', 'Group membership'), ('PARENT', 'Parent')], max_length=32)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_access_audit_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audit_logs', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Access Audit Log',
                'verbose_name_plural': 'Issue Access Audit Logs',
                'db_table': 'issue_access_audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['issue', 'created_at'], name='issue_access_audit_issue_idx'), models.Index(fields=['project', 'created_at'], name='issue_access_audit_project_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssueAccessGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_access_links', to='db.projectusergroup')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_group_links', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Access Group',
                'verbose_name_plural': 'Issue Access Groups',
                'db_table': 'issue_access_groups',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'group'), name='unique_active_issue_access_group')],
            },
        ),
    ]
